rec {
    pkgs =
        import (import ./nixpkgs.nix) {};

    ghc =
        pkgs.haskell.packages.ghc844.override {
            overrides =
                self:
                super:
                {
                    # Any version overrides can go here.
                    # They'll look like this:
                    #
                    #     foo = self.callPackage ./foo.nix {};
                    #
                    # where foo.nix is generated by cabal2nix.
                };
        };

    haskell =
        ghc.ghcWithPackages (p: [
            p.alex
            p.async
            p.cairo
            p.glib
            p.gtk3
            p.happy
            p.pango
            p.primitive
            p.random
            p.stm
            p.time
            p.transformers
            p.unix
        ]);

    ghcid =
        pkgs.haskellPackages.ghcid;

}
